var user = {
login: "adlondon",
id: 9470862,
avatar_url: "https://avatars.githubusercontent.com/u/9470862?v=3",
gravatar_id: "",
url: "https://api.github.com/users/adlondon",
html_url: "https://github.com/adlondon",
followers_url: "https://api.github.com/users/adlondon/followers",
following_url: "https://api.github.com/users/adlondon/following{/other_user}",
gists_url: "https://api.github.com/users/adlondon/gists{/gist_id}",
starred_url: "https://api.github.com/users/adlondon/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/adlondon/subscriptions",
organizations_url: "https://api.github.com/users/adlondon/orgs",
repos_url: "https://api.github.com/users/adlondon/repos",
events_url: "https://api.github.com/users/adlondon/events{/privacy}",
received_events_url: "https://api.github.com/users/adlondon/received_events",
type: "User",
site_admin: false,
name: "Andrew London",
company: null,
blog: null,
location: "Charleston, SC",
email: null,
hireable: null,
bio: null,
public_repos: 11,
public_gists: 0,
followers: 2,
following: 0,
created_at: "2014-10-30T22:29:37Z",
updated_at: "2016-02-17T01:22:35Z"
}
